version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017" # Agregué un espacio entre el guion y las comillas
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db